apiVersion: v1
kind: Service
metadata:
  name: weather-api-lb
spec:
  type: LoadBalancer
  selector:
    app: weather-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: weather-frontend-lb
spec:
  type: LoadBalancer
  selector:
    app: weather-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
